package tools.vitruv.methodologist.amalthea.asem.vsum;

import java.math.BigInteger;
import java.nio.file.Path;
import java.util.List;

import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl;

import org.eclipse.app4mc.amalthea.model.*;
import edu.kit.ipd.sdq.metamodels.asem.classifiers.*;
import edu.kit.ipd.sdq.metamodels.asem.dataexchange.*;
import edu.kit.ipd.sdq.metamodels.asem.primitivetypes.*;

import tools.vitruv.framework.views.View;
import tools.vitruv.framework.vsum.VirtualModel;
import tools.vitruv.framework.vsum.VirtualModelBuilder;

// generated by the Reactions language compiler from .reactions files
import tools.vitruv.methodologist.amalthea.asem.consistency.AmaltheaToAsemChangePropagationSpecification;
import tools.vitruv.methodologist.amalthea.asem.consistency.AsemToAmaltheaChangePropagationSpecification;

/**
 * VSUMRunner
 *
 * The single place where the VSUM is wired up and all helpers live.
 * Both test classes (AmaltheaToAsemTest and AsemToAmaltheaTest) call
 * only the static methods here — nothing about the VSUM setup leaks
 * into the test classes themselves.
 *
 * To run all tests from the command line:
 *
 *   mvn test -pl vsum
 *
 * To run a single test class:
 *
 *   mvn test -pl vsum -Dtest=AmaltheaToAsemTest
 *   mvn test -pl vsum -Dtest=AsemToAmaltheaTest
 *
 * To run a single test method:
 *
 *   mvn test -pl vsum -Dtest=AmaltheaToAsemTest#e1_componentCreated_moduleCreated
 *
 * In Eclipse: right-click either test class → Run As → JUnit Test.
 * Both test classes will appear together in the JUnit view.
 */
public final class VSUMRunner {

    private VSUMRunner() {
        // static utility — not instantiated
    }

    // ── VSUM wiring ───────────────────────────────────────────────────────────

    /**
     * Builds a fresh VirtualModel in the given directory.
     *
     * Registers:
     *   - AMALTHEA metamodel  (APP4MC 3.3.0)
     *   - ASEM metamodel      (KIT)
     *   - AmaltheaToAsem change propagation spec (compiled from .reactions)
     *   - AsemToAmalthea change propagation spec (compiled from .reactions)
     *
     * Called at the start of every @Test method so each test gets its own
     * isolated VSUM with no leftover state from previous tests.
     */
    public static VirtualModel createDefaultVirtualModel(Path tempDir) {
        return new VirtualModelBuilder()
                .withStorageFolder(tempDir)
                .withMetamodel(AmaltheaPackage.eINSTANCE)
                .withMetamodel(AsemPackage.eINSTANCE)
                .withChangePropagationSpecification(
                        new AmaltheaToAsemChangePropagationSpecification())
                .withChangePropagationSpecification(
                        new AsemToAmaltheaChangePropagationSpecification())
                .buildAndInitialize();
    }

    // ── View access ───────────────────────────────────────────────────────────

    /**
     * Returns a view on the VSUM showing all root objects whose runtime type
     * matches at least one entry in {@code rootTypes}.
     *
     * Used in tests to assert how many elements of a given type exist, e.g.:
     *   assertEquals(1, VSUMRunner.getView(vsum, List.of(Module.class))
     *                             .getRootObjects().size());
     */
    public static View getView(VirtualModel vsum,
                                List<Class<? extends EObject>> rootTypes) {
        return vsum.createSelector(selector ->
                selector.getSelectableElements().stream()
                        .filter(e -> rootTypes.stream().anyMatch(t -> t.isInstance(e)))
                        .forEach(selector::select)
        ).createView();
    }

    // ── Correspondence lookup ─────────────────────────────────────────────────

    /**
     * Returns the element of type {@code targetType} that the correspondence
     * model has registered for {@code source}, or null if none exists.
     *
     * Tests use assertNotNull / assertNull on the return value so that
     * JUnit failure messages are descriptive.
     */
    public static <T extends EObject> T getCorresponding(VirtualModel vsum,
                                                          EObject source,
                                                          Class<T> targetType) {
        return vsum.getCorrespondenceModel()
                   .getCorrespondingEObjects(source)
                   .stream()
                   .filter(targetType::isInstance)
                   .map(targetType::cast)
                   .findFirst()
                   .orElse(null);
    }

    // ── Element lifecycle ─────────────────────────────────────────────────────

    /**
     * Removes {@code element} from its container and propagates the deletion
     * to the VSUM so that the reactions can clean up the other model.
     */
    public static void deleteAndPropagate(VirtualModel vsum, EObject element) {
        var container = element.eContainer();
        if (container != null) {
            container.eContents().remove(element);
        } else if (element.eResource() != null) {
            element.eResource().getContents().remove(element);
        }
        vsum.propagateDeletion(element);
    }

    /**
     * Returns true when the element still exists in a loaded resource.
     * Returns false when the element was deleted (resource gone or unloaded).
     */
    public static boolean isAlive(EObject element) {
        if (element == null) return false;
        Resource res = element.eResource();
        return res != null && res.isLoaded();
    }

    // ── AMALTHEA element creation helpers ────────────────────────────────────

    /**
     * Creates an Amalthea root model containing a single Component, persists
     * it as a .amxmi file in tempDir, and propagates the creation to the VSUM.
     *
     * The VSUM reactions will automatically create a corresponding Module.
     */
    public static Component addComponent(VirtualModel vsum, Path tempDir, String name) {
        var amalthea  = AmaltheaFactory.eINSTANCE.createAmalthea();
        var compModel = AmaltheaFactory.eINSTANCE.createComponentsModel();
        amalthea.setComponentsModel(compModel);

        var component = AmaltheaFactory.eINSTANCE.createComponent();
        component.setName(name);
        compModel.getComponents().add(component);

        persistAndPropagate(vsum, tempDir, amalthea, "am_component_" + name + ".amxmi");
        return component;
    }

    /**
     * Adds a Runnable to an existing Component and propagates.
     * The VSUM reactions will create a corresponding void no-param Method.
     */
    public static Runnable addRunnable(VirtualModel vsum, Component component, String name) {
        var runnable = AmaltheaFactory.eINSTANCE.createRunnable();
        runnable.setName(name);
        component.getRunnables().add(runnable);
        vsum.propagateChange(runnable);
        return runnable;
    }

    /**
     * Adds a Label (with the given constant flag) to a Component and propagates.
     *
     * constant=false → reactions create a Message on the ASEM side (Rule 6 / E9)
     * constant=true  → reactions create a Constant on the ASEM side (Rule 5 / E10)
     */
    public static Label addLabel(VirtualModel vsum, Component component,
                                  String name, boolean constant) {
        var label = AmaltheaFactory.eINSTANCE.createLabel();
        label.setName(name);
        label.setConstant(constant);
        component.getLabels().add(label);
        vsum.propagateChange(label);
        return label;
    }

    /**
     * Creates a BaseTypeDefinition with the given size (bits) and optional
     * alias, persists it and propagates.
     *
     * Size and alias together determine which ASEM primitive is created:
     *   size=1                                → BooleanType        (Rule 7 / E14)
     *   size∈{8,16,32}, no float alias        → Discrete type      (Rule 8 / E15)
     *   size∈{32,64}, alias contains float    → ContinuousType     (Rule 9 / E16)
     */
    public static BaseTypeDefinition addBaseTypeDefinition(VirtualModel vsum, Path tempDir,
                                                            String name, int sizeBits,
                                                            String alias) {
        var btd = AmaltheaFactory.eINSTANCE.createBaseTypeDefinition();
        btd.setName(name);

        var ds = AmaltheaFactory.eINSTANCE.createDataSize();
        ds.setValue(BigInteger.valueOf(sizeBits));
        ds.setUnit(DataSizeUnit.BIT);
        btd.setSize(ds);

        if (alias != null) {
            var a = AmaltheaFactory.eINSTANCE.createAlias();
            a.setAlias(alias);
            a.setTarget("ASEM");
            btd.getAliases().add(a);
        }

        var amalthea = AmaltheaFactory.eINSTANCE.createAmalthea();
        var swModel  = AmaltheaFactory.eINSTANCE.createSWModel();
        amalthea.setSwModel(swModel);
        swModel.getTypeDefinitions().add(btd);

        persistAndPropagate(vsum, tempDir, amalthea, "am_btd_" + name + ".amxmi");
        return btd;
    }

    /**
     * Creates a DataTypeDefinition wrapping an Array and propagates.
     * The reactions create a corresponding ComposedType (Rule 10 / E17).
     */
    public static DataTypeDefinition addArrayTypeDefinition(VirtualModel vsum, Path tempDir,
                                                             String name, int elements) {
        var array = AmaltheaFactory.eINSTANCE.createArray();
        array.setNumberElements(elements);

        var dtd = AmaltheaFactory.eINSTANCE.createDataTypeDefinition();
        dtd.setName(name);
        dtd.setDataType(array);

        var amalthea = AmaltheaFactory.eINSTANCE.createAmalthea();
        var swModel  = AmaltheaFactory.eINSTANCE.createSWModel();
        amalthea.setSwModel(swModel);
        swModel.getTypeDefinitions().add(dtd);

        persistAndPropagate(vsum, tempDir, amalthea, "am_arr_" + name + ".amxmi");
        return dtd;
    }

    // ── ASEM element creation helpers ─────────────────────────────────────────

    /**
     * Creates an ASEM model containing a single Module, persists it and
     * propagates. The reactions will create a corresponding Component (Rule 1 / E3).
     */
    public static Module addModule(VirtualModel vsum, Path tempDir, String name) {
        var module = AsemFactory.eINSTANCE.createModule();
        module.setName(name);
        persistAndPropagate(vsum, tempDir, module, "asem_module_" + name + ".asem");
        return module;
    }

    /**
     * Adds a void, no-parameter Method to a Module and propagates.
     *
     * returnType is intentionally left null and parameters left empty.
     * This is required by the Rule 4 OCL invariant; Methods that violate it
     * are not propagated to AMALTHEA as Runnables.
     */
    public static Method addVoidMethod(VirtualModel vsum, Module module, String name) {
        var method = AsemFactory.eINSTANCE.createMethod();
        method.setName(name);
        // returnType stays null  — OCL: self.returnType.oclIsUndefined()
        // parameters left empty  — OCL: self.parameters->size() = 0
        module.getMethods().add(method);
        vsum.propagateChange(method);
        return method;
    }

    /**
     * Adds a Message to a Module's typedElements and propagates.
     * The reactions create a corresponding Label with constant=false (Rule 6 / E12).
     */
    public static Message addMessage(VirtualModel vsum, Module module, String name) {
        var message = AsemFactory.eINSTANCE.createMessage();
        message.setName(name);
        module.getTypedElements().add(message);
        vsum.propagateChange(message);
        return message;
    }

    /**
     * Adds a Constant to a Module's typedElements and propagates.
     * The reactions create a corresponding Label with constant=true (Rule 5 / E13).
     */
    public static Constant addConstant(VirtualModel vsum, Module module, String name) {
        var constant = AsemFactory.eINSTANCE.createConstant();
        constant.setName(name);
        module.getTypedElements().add(constant);
        vsum.propagateChange(constant);
        return constant;
    }

    // ── Private: persist a model root to disk and notify the VSUM ────────────

    private static void persistAndPropagate(VirtualModel vsum, Path tempDir,
                                             EObject root, String fileName) {
        ResourceSet rs  = new ResourceSetImpl();
        URI uri         = URI.createFileURI(tempDir.resolve(fileName).toString());
        Resource res    = rs.createResource(uri);
        res.getContents().add(root);
        try {
            res.save(null);
        } catch (Exception e) {
            throw new RuntimeException("Failed to persist model: " + uri, e);
        }
        vsum.propagateChange(root);
    }
}
